name: charge-tracker
version: "1.0.4"
slug: charge-tracker
description: Track and visualize your EV charging sessions
url: "https://github.com/doppelrittberger/charge-tracker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
image: "doppelrittberger/charge-tracker"
boot: auto
legacy: true
stage: stable
ingress: true
ingress_port: 8080
init: false
watchdog: http://[HOST]:[PORT:8080]
webui: http://[HOST]:[PORT:8080]/
map:
  - share:rw
environment:
  CHARGE_TRACKER_DATA_FILE: /share/charge-sessions.json
startup: application
panel_icon: mdi:ev-station
panel_admin: false
panel_title: Ladevorgänge
