name: charge-tracker
version: "1.1.5"
slug: charge-tracker
description: Track and visualize your EV charging sessions
url: "https://github.com/doppelrittberger/charge-tracker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
image: "doppelrittberger/charge-tracker"
boot: auto
legacy: true
stage: stable
ingress: true
ingress_port: 8080
host_network: true
init: false
watchdog: http://[HOST]:[PORT:8080]
webui: http://[HOST]:[PORT:8080]/
map:
  - share:rw
options:
  evcc_url: http://[HOST]:7070
  evcc_import_enabled: false
  ha_url: http://[HOST]:8123
  ha_token: ""
  ha_enabled: false
  ha_odometer_entity: sensor.skoda_elroq_kilometerstand
  ha_soc_entity: sensor.skoda_elroq_batteriestand
  vehicle_battery_capacity_kwh: 77.0
  charge_tracker_data_file: /share/charge-sessions.json
schema:
  evcc_url: str
  evcc_import_enabled: bool
  ha_url: str
  ha_token: str
  ha_enabled: bool
  ha_odometer_entity: str
  ha_soc_entity: str
  vehicle_battery_capacity_kwh: float
  charge_tracker_data_file: str
startup: application
panel_icon: mdi:ev-station
panel_admin: false
panel_title: Ladevorgänge
