quarkus.http.port=8080
quarkus.qute.content-types.html=text/html;charset=UTF-8
charge.tracker.data-file=charge-sessions.json
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.enable-forwarded-prefix=true
